language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la

install:
  - npm install

script:
  - npm run build
  - npm run test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  